Cimcore importer
standardhealth/shr-expand pull request #32
Opened 2018-06-27 15:35 UTC by Abhijay

Hold off on reviewing this for now. Paired with 3 other PRs.

2018-07-12 20:26 UTC, cmoesel requested changes
I commented on one minor thing to consider adjusting, but the main issue is that if you run the tests, 17 of them fail (probably because the fixtures need to be updated).

2018-07-12 20:26 UTC, cmoesel commented on lib/expand.js
> +              // if (!(parent.value instanceof models.TBD)) {
If we really don't want this code (or the commented out code two lines below it), we should _delete_ it.  Otherwise we need to at least state why it's commented out.

2018-07-12 20:26 UTC, cmoesel commented on lib/expand.js
> +            // return;
If this is an empty `if` block, followed by an `else`, wouldn't it make sense to replace it by a single if block that is the negation of the original condition?

i.e., shouldn't we convert the current `if/else` to just `if(!child.effectiveCard.equals(child.card))`?

2018-08-03 13:58 UTC, Abhijay commented
The last three commits should address your requested reviews as well as fixed the import unit tests.

Additionally, I fixed 2 unit tests that stemmed from `shr-models` (resolved in: https://github.com/standardhealth/shr-models/pull/25/commits/e9252b34952fb4ea8debe32ba203050306d1f4bd).

Note: This will require the package.json and yarn.lock file to be updated (to match `shr-models` `v5.2.3`)

2018-09-12 17:56 UTC, cmoesel commented
I rebased on master and added a commit to fix some broken tests.

Version number and dependencies need to be bumped during the release process.

2018-09-13 12:57 UTC, cmoesel approved these changes

2018-09-13 12:57 UTC, merged