Decentralize loggerific errorMessages.txt
standardhealth/shr-expand pull request #45
Opened 2019-08-27 12:23 UTC by ngfreiter

This takes the `errorMessages.txt` file which existed only in `shr-cli` and splits it into multiple files, so that each module has its own `errorMessages.txt` file. Also incorrectly numbered or otherwise broken errors were fixed. Tests that depended on the old error messages format were refactored.

PR 3/7
Affects:
- `shr-cli`
- `shr-text-import`
- `shr-expand`
- `shr-fhir-export`
- `shr-json-schema-export`
- `shr-json-javadoc`
- `shr-es6-export`

2019-08-28 14:13 UTC, cmoesel requested changes
Only one minor thing to address (`path.join`).

2019-08-28 14:13 UTC, cmoesel commented on lib/expand.js
> +            logger.debug({ tbdText: basedOn.toString(), child: de.identifier.toString() }, '02002');
This is totally fine, but I think that in these cases `basedOn.fqn` and `de.identifier.fqn` would have worked too.  You don't need to change it, I just wanted to be sure you're aware of it.

2019-08-28 14:13 UTC, cmoesel commented on lib/expand.js
> +  return require('path').join(__dirname, '../errorMessages.txt');
```javascript
  return require('path').join(__dirname, '..', 'errorMessages.txt');
```

2019-08-28 14:13 UTC, cmoesel commented on test/expand-test.js
> +    expect(err.errors()[0].newValue2).to.eql('decimal');
I'm sure this was very annoying to have to actual modify all these tests, but... I really like the way they came out.  Seems much more structured than the previous approach of just looking for substrings.  So that's nice...

2019-08-28 15:11 UTC, ngfreiter commented on lib/expand.js
> +  return require('path').join(__dirname, '../errorMessages.txt');
Fixed this here https://github.com/standardhealth/shr-expand/pull/45/commits/688eb24c41b30429e0bfe179ed027d25110224e0.

2019-08-28 17:30 UTC, cmoesel commented
Changes all look good.  Holding off on merging pending a decision on whether we want this in master yet.  See: https://github.com/standardhealth/shr-cli/pull/227#pullrequestreview-280987415

2019-09-11 18:49 UTC, cmoesel approved these changes
Looks good.  I may squash or rebase this to clean up commits before merging.

2019-09-11 21:19 UTC, merged